### ISSUE TITLE
Could you add a readme?

### ISSUE THREAD

**Issue by hitecSmartHome** [mlesniew/PsychicWebSocketProxy#2]
HI! 
I have a project in mind where I want to create an IDF websocket client to PsychicHTTP adapter.
The idea is that what comes from ws client, goes trought PsychicServer as it was a regular HTTP request and the response should also be routed back on websockets.

Is this project similar?

Thank you very much!

**Comment by mlesniew** [comment]
The nice summer weather was keeping me away from my computer recently, but don't worry, I'm planning to add a readme soon!

I'm not sure if I understand what you're trying to build correctly, but it looks like this project is trying to achieve something different.

PsychicHTTP is asynchronous and internally the IDF server API (for both websockets and http requests).  Now because it's asynchronous, it's incompatible with some of the libraries from the Arduino world, which can only work in a synchronous fashion.  

This library aims to provide a kind of adapter to connect the PsychicHTTP server's websocket to synchronous libraries that need something that has an interface similar to [EthernetServer](https://www.arduino.cc/reference/en/libraries/ethernet/ethernetserver/) or its WiFi cousins on the ESP32.

The main purpose was to use it with [PicoMQTT](https://github.com/mlesniew/PicoMQTT), a synchronous MQTT broker and client library, but it should work in other scenarios and with other libraries too.

Until the readme is ready, you can explore the examples in this repo to see how to use it and how it works.

**Comment by hitecSmartHome** [comment]
Thank you for the answer. From the name, I tought it converts websocket frames to PsychicHttp requests. Sorry. 

My goal is to setup a wss client which connects to a server in the cloud. When the server gets an http request, it will route the entire request to an esp32 via wss.

When the esp32 got a wss frame, it will parse it as a PsychicHttp request and route it trought the PsychicHttpServer.

That way I can host the same web app on the cloud without writing duplicate code on the esp32 and it will think that the requests comes from a regular local http.

The problem is that I have to differentiate the requests and build a response accordingly. Since it has to send the response back on wss.

Nevermind. Thank you very much for the help.
